# Generated by Django 3.1.2 on 2020-11-14 11:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('resensi', models.TextField(help_text='Tuliskan deskripsi singkat buku ini', max_length=1000)),
                ('isbn', models.CharField(help_text='13 Karakter <a href="https://www.isbn-international.org/content/what-isbn">nomor ISBN</a>', max_length=13, unique=True, verbose_name='ISBN')),
            ],
        ),
        migrations.CreateModel(
            name='Jenis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Masukkan jenis buku (misalnya: Sastra)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Penulis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_depan', models.CharField(max_length=100)),
                ('nama_belakang', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('tanggal_wafat', models.DateField(blank=True, null=True, verbose_name='Wafat')),
            ],
            options={
                'ordering': ['nama_belakang', 'nama_depan'],
            },
        ),
        migrations.CreateModel(
            name='InstanceBuku',
            fields=[
                ('kode', models.UUIDField(default=uuid.uuid4, help_text='Kode unik untuk buku tertentu di seluruh perpustakaan', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('kembali', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('p', 'diperbaiki'), ('s', 'disewa'), ('a', 'ada'), ('b', 'dipesan')], default='p', help_text='Ketersediaan buku', max_length=1)),
                ('buku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='katalog.buku')),
            ],
            options={
                'ordering': ['kembali'],
            },
        ),
        migrations.AddField(
            model_name='buku',
            name='jenis',
            field=models.ManyToManyField(help_text='Pilih jenis/aliran buku ini', to='katalog.Jenis'),
        ),
        migrations.AddField(
            model_name='buku',
            name='penulis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='katalog.penulis'),
        ),
    ]
