# Generated by Django 3.1.2 on 2020-11-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0006_auto_20201125_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buku',
            options={'ordering': ['judul'], 'verbose_name': 'Buku', 'verbose_name_plural': 'Buku'},
        ),
        migrations.AddField(
            model_name='buku',
            name='sampul',
            field=models.ImageField(null=True, upload_to='Bukus'),
        ),
    ]
