# Generated by Django 3.1.2 on 2020-11-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0007_auto_20201129_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buku',
            name='sampul',
            field=models.ImageField(null=True, upload_to='katalog/gambar'),
        ),
    ]
